if(getRversion() >= "2.15.1")
  utils::globalVariables(c(".",
                           "SurveyLength",
                           "Zscore",
                           "check",
                           "days_worked",
                           "duration_mean",
                           "ind",
                           "nb",
                           "surveytime",
                           "total_surveys_done",
                           "values",
                           "%>%",
                           "%like%",
                           "add_trace",
                           "count_",
                           "funs",
                           "group_by",
                           "group_by_",
                           "left_join mutate",
                           "n",
                           "n_distinct",
                           "select",
                           "summarise_all",
                           "summarize summarize_",
                           "left_join",
                           "mutate",
                           "summarize",
                           "summarize_",
                           "Outside"))
